### ISSUE TITLE
No auto-play, does not stop when starting a game.

### ISSUE THREAD

**Issue by Sesquipedal** [Naprosnia/RetroPie_BGM_Player#4]
Hello, 
I installed as you directed.  I see the BGM-Player in the retropie config menu.
I don't hear any music from when I start the retropie.  I have restarted many times from cold as well.
If I go into the BGM setting turn it off then on again, it starts playing.
However when I enter a game it does not turn off.
I restarted after that, and the music is still not autoplaying on startup.
In the BGM menu the non-stop option is unchanged form default which is off.

Something isn't right here with my setup.  
What are some things I can check?

**Comment by Naprosnia** [comment]
Hello, You are installing it on RetroPie? Or other system like Recalbox?
Enter command line with F4, and execute:
`ls -l /opt/retropie/configs/all`

It will display all files inside that folder.
Let me know if you find autostart.sh, runcommand-onstart.sh and runcommand-onend.sh.

If you find them or any, send me the text you see on the respective line (date and hours not nedded).

And if you find any of this files please execute to display their content. Let me know if you find any line containing the word  bgm_system.sh. 
`cat /opt/retropie/configs/all/autostart.sh`
`cat /opt/retropie/configs/all/runcommand-onstart.sh`
`cat /opt/retropie/configs/all/runcommand-onend.sh`

**Comment by Sesquipedal** [comment]
Thank you kindly for helping me!
This is on a retropie.
I do not see runcommand-onstart.sh and runcommand-onend.sh.
I do see two runcommand files but they are not the same and are .cfg.

The only thing that is in the autostart.sh is a no-splash command so I don't need that emulationstation splash.    

Looks like nothing was written during install then?

**Comment by Naprosnia** [comment]
Maybe you got wrong permissions on configs,
/all folder. Install bgm player again, don't need to uninstall, I add some code to force permission correction.

**Comment by Sesquipedal** [comment]
Worked perfectly!  I wonder what caused my permissions to change as it's a new install minus the no splash and some themes.  Oh well, thank you kindly for your help.   I noticed others were having a similar issue after installing older BGM attempts so perhaps this will help someone else as well.
