### ISSUE TITLE
Can I play only music in my folders?

### ISSUE THREAD

**Issue by palla89** [Naprosnia/RetroPie_BGM_Player#5]
Hi! Thank you for this amazing plugin!
I encountered this problem and I'd like to know if you can help me:

I installed everything and it works fine, then I put my custom vgm and vgz in the music folders and everything is fine. The problem is that it plays also music I didn't put! 
Is the plugin also searching for files in the roms folders besides the music one? I think it's an awesome feature but it would be great to be just able to play the music we inserted without "random" ones.

What do you think about it?

**Comment by Naprosnia** [comment]
Hello, You need to remove the files that you dont want from music folder, or it will find them and play with others that you put there.

**Comment by palla89** [comment]
Thank you for your quick answer! I understood only now why I was hearing "other songs":
I kept from your folder only the music of supermario and I opened it just for a quick listening with VLC, that let me hear the first track, I didn't know that the .nsf file can have many tracks! 

Sorry for the false alarm!
